# Generated by Django 5.2.14 on 2026-05-07 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL hình ảnh')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá bán')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá gốc')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('is_new', models.BooleanField(default=False, verbose_name='Sản phẩm mới')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Sản phẩm hot')),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Giảm giá (%)')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='Thông số kỹ thuật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('supplier', models.ForeignKey(db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=500, verbose_name='URL hình ảnh')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hình chính')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Hình ảnh',
                'verbose_name_plural': 'Hình ảnh',
                'db_table': 'ProductImages',
                'ordering': ['display_order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Màu sắc')),
                ('storage', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dung lượng')),
                ('ram', models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM')),
                ('variant_name', models.CharField(max_length=100, verbose_name='Tên biến thể')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá gốc')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Biến thể',
                'verbose_name_plural': 'Biến thể',
                'db_table': 'ProductVariants',
                'ordering': ['display_order', 'variant_name'],
            },
        ),
    ]
