# Generated by Django - Add variant, is_thumbnail, alt_text to ProductImage

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False, verbose_name='Hình thu nhỏ'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(
                blank=True,
                db_column='variant_id',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='products.productvariant'
            ),
        ),
    ]
