# Generated by Django 5.2.14 on 2026-05-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_variant_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['display_order', '-is_primary', '-image_id'], 'verbose_name': 'Hình ảnh', 'verbose_name_plural': 'Hình ảnh'},
        ),
    ]
