# Generated by Django 5.2.14 on 2026-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(default='box', help_text='Tên icon Bootstrap Icons, ví dụ: mobile-alt, laptop, headphones', max_length=50, verbose_name='Tên icon'),
        ),
    ]
