# Generated by Django 5.2.14 on 2026-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Câu hỏi')),
                ('answer', models.TextField(verbose_name='Câu trả lời')),
                ('category', models.CharField(choices=[('General', 'Câu hỏi chung'), ('Order', 'Về đơn hàng'), ('Payment', 'Thanh toán'), ('Shipping', 'Vận chuyển'), ('Return', 'Đổi trả'), ('Product', 'Sản phẩm')], default='General', max_length=50, verbose_name='Danh mục')),
                ('keywords', models.TextField(blank=True, help_text='Các từ khóa liên quan, cách nhau bởi dấu phẩy', null=True, verbose_name='Từ khóa')),
                ('priority', models.IntegerField(default=0, help_text='Số càng lớn càng ưu tiên hiển thị', verbose_name='Độ ưu tiên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'FAQs',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
