# Generated by Django 5.2.14 on 2026-05-10 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Session key (Guest)'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
