# Generated by Django 5.2.14 on 2026-05-07 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Tên đăng nhập')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Mật khẩu')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ tên')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('role', models.CharField(choices=[('Admin', 'Quản trị viên'), ('Employee', 'Nhân viên'), ('Customer', 'Khách hàng')], default='Customer', max_length=20, verbose_name='Vai trò')),
                ('reset_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token reset')),
                ('reset_token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Tài khoản',
                'db_table': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=10, unique=True, verbose_name='Mã nhân viên')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng ban')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chức vụ')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ngày vào làm')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Lương')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('account', models.OneToOneField(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'Employees',
            },
        ),
    ]
