# Generated by Django 5.2.14 on 2026-05-10 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Han cua token')),
                ('used', models.BooleanField(default=False, verbose_name='Da su dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reset mat khau',
                'verbose_name_plural': 'Reset mat khau',
                'db_table': 'PasswordResets',
                'ordering': ['-created_at'],
            },
        ),
    ]
