# Generated by Django 5.2.14 on 2026-05-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_productimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('low_stock_threshold', models.IntegerField(default=10, verbose_name='Ngưỡng báo động')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
                'db_table': 'Inventory',
            },
        ),
    ]
