# Generated by Django 5.2.14 on 2026-05-10 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        ('products', '0003_alter_productimage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Nhap kho'), ('OUT', 'Xuat kho'), ('ADJUST', 'Dieu chinh'), ('RETURN', 'Tra hang')], max_length=20, verbose_name='Loai bien dong')),
                ('quantity', models.IntegerField(verbose_name='So luong')),
                ('reason', models.CharField(max_length=200, verbose_name='Ly do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product')),
                ('related_order', models.ForeignKey(blank=True, db_column='related_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='orders.order')),
            ],
            options={
                'verbose_name': 'Bien dong kho',
                'verbose_name_plural': 'Bien dong kho',
                'db_table': 'InventoryMovements',
                'ordering': ['-created_at'],
            },
        ),
    ]
