# Generated by Django 5.2.14 on 2026-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Bật chế độ bảo trì')),
                ('message', models.TextField(default='Website đang được bảo trì. Vui lòng quay lại sau.', verbose_name='Thông báo')),
                ('allowed_ips', models.TextField(blank=True, help_text='Mỗi IP trên 1 dòng', verbose_name='IP được phép truy cập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'db_table': 'MaintenanceMode',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Tên biến cài đặt (không dấu, gạch dưới)', max_length=100, unique=True, verbose_name='Key')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Giá trị')),
                ('setting_type', models.CharField(choices=[('text', 'Văn bản'), ('number', 'Số'), ('boolean', 'Boolean'), ('image', 'Hình ảnh'), ('json', 'JSON')], default='text', max_length=20, verbose_name='Loại')),
                ('category', models.CharField(choices=[('general', 'Chung'), ('contact', 'Liên hệ'), ('social', 'Mạng xã hội'), ('email', 'Email'), ('payment', 'Thanh toán'), ('seo', 'SEO'), ('other', 'Khác')], default='general', max_length=20, verbose_name='Danh mục')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('is_public', models.BooleanField(default=False, help_text='Cho phép hiển thị ở frontend', verbose_name='Hiển thị công khai')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Cài đặt',
                'verbose_name_plural': 'Cài đặt',
                'db_table': 'SiteSettings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
