# Generated by Django 5.2.14 on 2026-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('slide_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phụ đề')),
                ('image_url', models.CharField(max_length=500, verbose_name='URL hình ảnh')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link liên kết')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Text nút bấm')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'db_table': 'Slides',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
