# -*- coding: utf-8 -*-
from pathlib import Path

content = (
    "{% extends \"Shared/base.html\" %}\n"
    "\n"
    "{% block extra_head %}\n"
    "<style>\n"
    "/* PMO Modal */\n"
    ".pmo-overlay{position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:9990;display:none;align-items:center;justify-content:center;padding:16px;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}\n"
    ".pmo-overlay.active{display:flex}\n"
    ".pmo-modal{background:#fff;border-radius:18px;width:100%;max-width:440px;max-height:88vh;overflow-y:auto;box-shadow:0 24px 80px rgba(0,0,0,.18);animation:pmoIn .3s ease;font-family:'Inter',sans-serif}\n"
    "@keyframes pmoIn{from{opacity:0;transform:translateY(16px) scale(.96)}to{opacity:1;transform:translateY(0) scale(1)}}\n"
    ".pmo-hdr{display:flex;align-items:center;padding:18px;border-bottom:1px solid var(--border-sub);gap:14px}\n"
    ".pmo-thumb{width:68px;height:68px;border-radius:12px;background:var(--bg);display:flex;align-items:center;justify-content:center;overflow:hidden;border:1px solid var(--border-sub);flex-shrink:0}\n"
    ".pmo-thumb img{max-width:100%;max-height:100%;object-fit:contain}\n"
    ".pmo-info{flex:1;min-width:0}\n"
    ".pmo-name{font-size:.92rem;font-weight:600;color:var(--text);margin-bottom:3px;line-height:1.3}\n"
    ".pmo-price{font-size:1.05rem;font-weight:700;color:var(--rose)}\n"
    ".pmo-close{width:34px;height:34px;border-radius:50%;border:none;background:var(--bg-hover);color:var(--text-sec);cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:all .15s;font-size:.85rem}\n"
    ".pmo-close:hover{background:var(--rose);color:#fff}\n"
    ".pmo-body{padding:18px}\n"
    ".pmo-opt-label{font-size:.72rem;font-weight:700;color:var(--text-sec);margin-bottom:9px;text-transform:uppercase;letter-spacing:.5px}\n"
    ".pmo-opt-row{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:18px}\n"
    ".pmo-opt{padding:7px 14px;border-radius:999px;border:1.5px solid var(--border);font-size:.8rem;font-weight:600;cursor:pointer;transition:all .2s;background:#fff;color:var(--text);font-family:'Inter',sans-serif}\n"
    ".pmo-opt:hover{border-color:var(--blue);color:var(--blue)}\n"
    ".pmo-opt.selected{border-color:var(--blue);background:var(--blue-pale);color:var(--blue)}\n"
    ".pmo-opt:disabled{opacity:.4;cursor:not-allowed}\n"
    ".pmo-dot{display:inline-block;width:11px;height:11px;border-radius:50%;vertical-align:middle;margin-right:4px;border:1px solid rgba(0,0,0,.1)}\n"
    ".pmo-qty{display:flex;align-items:center;gap:12px;margin-bottom:18px}\n"
    ".pmo-qty-lbl{font-size:.82rem;font-weight:600;color:var(--text-sec)}\n"
    ".pmo-qty-ctrl{display:flex;align-items:center;border:1.5px solid var(--border);border-radius:10px;overflow:hidden}\n"
    ".pmo-qty-btn{width:36px;height:36px;border:none;background:#fff;color:var(--text);font-size:.95rem;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:all .12s}\n"
    ".pmo-qty-btn:hover{background:var(--bg-hover)}\n"
    ".pmo-qty-val{width:46px;height:36px;display:flex;align-items:center;justify-content:center;font-size:.9rem;font-weight:700;color:var(--text);border-left:1.5px solid var(--border);border-right:1.5px solid var(--border)}\n"
    ".pmo-foot{padding:14px 18px;border-top:1px solid var(--border-sub)}\n"
    ".pmo-add-btn{width:100%;padding:13px;border-radius:12px;font-size:.9rem;font-weight:700;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:7px;font-family:'Inter',sans-serif;transition:all .25s;background:var(--blue);color:#fff;border:none}\n"
    ".pmo-add-btn:hover{background:var(--blue-hover);box-shadow:0 6px 20px rgba(0,113,227,.3);transform:translateY(-1px)}\n"
    ".pmo-add-btn:disabled{opacity:.5;cursor:not-allowed}\n"
    ".pmo-loading{display:flex;align-items:center;justify-content:center;padding:48px;color:var(--text-sec);font-size:.85rem}\n"
    "</style>\n"
    "{% endblock %}\n"
    "\n"
    "{% block content %}\n"
    "\n"
    "<!-- HERO -->\n"
    "<section class=\"hero\">\n"
    "  <div class=\"hero-inner\">\n"
    "    <div class=\"hero-content\">\n"
    "      <div class=\"hero-eyebrow\"><i class=\"fas fa-bolt\"></i> AI Shopping Assistant</div>\n"
    "      <h1 class=\"hero-title\">C\u00f4ng ngh\u1ec7 <em>th\u00f4ng minh h\u01a1n</em></h1>\n"
    "      <p class=\"hero-desc\">Tr\u1ea3i nghi\u1ec7m mua s\u1eafp c\u00f4ng ngh\u1ec7 v\u1edbi tr\u1ee3 l\u00fd AI th\u00f4ng minh, t\u01b0 v\u1ea5n s\u1ea3n ph\u1ea9m ph\u00f9 h\u1ee3p 24/7. H\u00e0ng ch\u00ednh h\u00e3ng, gi\u00e1 t\u1ed1t nh\u1ea5t th\u1ecb tr\u01b0\u1eddng.</p>\n"
    "      <div class=\"hero-btns\">\n"
    "        <a href=\"/Products/\" class=\"hero-btn hero-btn-primary\"><i class=\"fas fa-bolt\"></i> Mua s\u1eafp ngay</a>\n"
    "        <a href=\"/Products/\" class=\"hero-btn hero-btn-secondary\"><i class=\"fas fa-eye\"></i> Xem s\u1ea3n ph\u1ea9m</a>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div class=\"hero-visual\">\n"
    "      <div class=\"hero-product-card\">\n"
    "        <div class=\"hero-product-img\"><i class=\"fas fa-mobile-alt\"></i></div>\n"
    "        <div class=\"hero-product-name\">iPhone 15 Pro Max</div>\n"
    "        <div class=\"hero-product-rating\"><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i></div>\n"
    "        <div class=\"hero-product-price\">24.990.000 \u0111 &nbsp;<span class=\"hero-product-orig\">27.990.000 \u0111</span></div>\n"
    "        <a href=\"/Products/\" class=\"hero-product-btn\"><i class=\"fas fa-cart-plus\"></i> Mua ngay</a>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</section>\n"
    "\n"
    "<!-- TRUST -->\n"
    "<section style=\"padding:36px 0;background:var(--bg-white);border-bottom:1px solid var(--border-sub)\">\n"
    "  <div class=\"container\">\n"
    "    <div class=\"trust-grid\">\n"
    "      <div class=\"trust-card\">\n"
    "        <div class=\"trust-icon blue\"><i class=\"fas fa-shield-alt\"></i></div>\n"
    "        <div><div class=\"trust-title\">Ch\u00ednh h\u00e3ng 100%</div><div class=\"trust-desc\">Cam k\u1ebft h\u00e0ng ch\u00ednh h\u00e3ng</div></div>\n"
    "      </div>\n"
    "      <div class=\"trust-card\">\n"
    "        <div class=\"trust-icon green\"><i class=\"fas fa-truck-fast\"></i></div>\n"
    "        <div><div class=\"trust-title\">Giao h\u00e0ng nhanh</div><div class=\"trust-desc\">Giao 2-4 gi\u1edd n\u1ed9i th\u00e0nh</div></div>\n"
    "      </div>\n"
    "      <div class=\"trust-card\">\n"
    "        <div class=\"trust-icon amber\"><i class=\"fas fa-rotate-left\"></i></div>\n"
    "        <div><div class=\"trust-title\">\u0110\u1ed5i tr\u1ea3 7 ng\u00e0y</div><div class=\"trust-desc\">Mi\u1ec5n ph\u00ed \u0111\u1ed5i tr\u1ea3 trong tu\u1ea7n</div></div>\n"
    "      </div>\n"
    "      <div class=\"trust-card\">\n"
    "        <div class=\"trust-icon purple\"><i class=\"fas fa-headset\"></i></div>\n"
    "        <div><div class=\"trust-title\">H\u1ed7 tr\u1ee3 24/7</div><div class=\"trust-desc\">T\u01b0 v\u1ea5n online m\u1ecdi l\u00fac</div></div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</section>\n"
    "\n"
    "<!-- CATEGORIES -->\n"
    "<section class=\"section\">\n"
    "  <div class=\"container\">\n"
    "    <div class=\"section-header\">\n"
    "      <div>\n"
    "        <div class=\"section-label\">Kh\u00e1m ph\u00e1</div>\n"
    "        <div class=\"section-title\">Danh m\u1ee5c s\u1ea3n ph\u1ea9m</div>\n"
    "      </div>\n"
    "      <a href=\"/Products/\" class=\"section-link\">Xem t\u1ea5t c\u1ea3 <i class=\"fas fa-arrow-right\"></i></a>\n"
    "    </div>\n"
    "    <div class=\"cat-grid\">\n"
    "      {% for cat in categories %}\n"
    "      <a href=\"/Products/?category_id={{ cat.category_id }}\" class=\"cat-card\">\n"
    "        <div class=\"cat-icon\"><i class=\"fas fa-mobile-alt\"></i></div>\n"
    "        <div class=\"cat-name\">{{ cat.name }}</div>\n"
    "        <div class=\"cat-count\">{{ cat.products | length if cat.products else '' }} s\u1ea3n ph\u1ea9m</div>\n"
    "      </a>\n"
    "      {% endfor %}\n"
    "      {% if not categories %}\n"
    "      <a href=\"/Products/?category_id=1\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-mobile-alt\"></i></div><div class=\"cat-name\">\u0110i\u1ec7n tho\u1ea1i</div><div class=\"cat-count\">24 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      <a href=\"/Products/?category_id=2\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-laptop\"></i></div><div class=\"cat-name\">Laptop</div><div class=\"cat-count\">18 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      <a href=\"/Products/?category_id=3\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-tablet-alt\"></i></div><div class=\"cat-name\">Tablet</div><div class=\"cat-count\">12 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      <a href=\"/Products/?category_id=4\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-headphones\"></i></div><div class=\"cat-name\">Tai nghe</div><div class=\"cat-count\">20 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      <a href=\"/Products/?category_id=5\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-keyboard\"></i></div><div class=\"cat-name\">Ph\u1ee5 ki\u1ec7n</div><div class=\"cat-count\">35 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      <a href=\"/Products/?category_id=6\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-clock\"></i></div><div class=\"cat-name\">\u0110\u1ed3ng h\u1ed3 th\u00f4ng minh</div><div class=\"cat-count\">15 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      <a href=\"/Products/?category_id=7\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-mouse\"></i></div><div class=\"cat-name\">B\u00e0n ph\u00edm & Chu\u1ed9t</div><div class=\"cat-count\">28 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      <a href=\"/Products/?category_id=8\" class=\"cat-card\"><div class=\"cat-icon\"><i class=\"fas fa-camera\"></i></div><div class=\"cat-name\">M\u00e1y \u1ea3nh</div><div class=\"cat-count\">10 s\u1ea3n ph\u1ea9m</div></a>\n"
    "      {% endif %}\n"
    "    </div>\n"
    "  </div>\n"
    "</section>\n"
    "\n"
    "<!-- PRODUCTS -->\n"
    "<section class=\"section section-alt\">\n"
    "  <div class=\"container\">\n"
    "    <div class=\"section-header\">\n"
    "      <div>\n"
    "        <div class=\"section-label\">S\u1ea3n ph\u1ea9m</div>\n"
    "        <div class=\"section-title\">S\u1ea3n ph\u1ea9m n\u1ed5i b\u1eadt</div>\n"
    "      </div>\n"
    "      <a href=\"/Products/\" class=\"section-link\">Xem t\u1ea5t c\u1ea3 <i class=\"fas fa-arrow-right\"></i></a>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"tabs\">\n"
    "      <button class=\"tab-btn active\" onclick=\"switchTab(event,'tab-new')\"><i class=\"fas fa-bolt\"></i> M\u1edbi nh\u1ea5t</button>\n"
    "      <button class=\"tab-btn\" onclick=\"switchTab(event,'tab-hot')\"><i class=\"fas fa-fire\"></i> Hot nh\u1ea5t</button>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"tab-new\" class=\"tab-content active\">\n"
    "      <div class=\"products-grid\">\n"
    "        {% if new_products %}\n"
    "          {% for product in new_products %}\n"
    "          <div class=\"product-card\">\n"
    "            <a href=\"/Products/{{ product.product_id }}\" class=\"product-img\">\n"
    "              {% if product.is_new %}<span class=\"product-badge badge-new\">M\u1edbi</span>{% endif %}\n"
    "              {% if product.is_hot %}<span class=\"product-badge badge-hot\" style=\"left:58px\">Hot</span>{% endif %}\n"
    "              {% if product.discount_percent > 0 %}<span class=\"product-discount\">-{{ product.discount_percent }}%</span>{% endif %}\n"
    "              <img src=\"{% set imgs = product.product_images|selectattr('is_primary')|list %}{% if imgs and imgs[0].image_url %}{{ imgs[0].image_url }}{% elif product.image_url %}{{ product.image_url }}{% elif product.product_images %}{{ product.product_images[0].image_url }}{% else %}/static/images/no-image.png{% endif %}\" alt=\"{{ product.name }}\" onerror=\"this.src='/static/images/no-image.png'\" />\n"
    "            </a>\n"
    "            <div class=\"product-body\">\n"
    "              <a href=\"/Products/{{ product.product_id }}\" class=\"product-name\">{{ product.name }}</a>\n"
    "              <div class=\"product-rating\">\n"
    "                <span class=\"product-stars\"><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star-half-alt\"></i></span>\n"
    "                <span class=\"product-reviews\">({{ product.rating | default(4.5) }})</span>\n"
    "              </div>\n"
    "              <div class=\"product-price-wrap\">\n"
    "                <span class=\"product-price\">{{ \"{:,.0f}\".format(product.price | float) if product.price else '0' }} \u0111</span>\n"
    "                {% if product.original_price and product.original_price > product.price %}\n"
    "                <span class=\"product-price-orig\">{{ \"{:,.0f}\".format(product.original_price | float) }} \u0111</span>\n"
    "                {% endif %}\n"
    "              </div>\n"
    "              <button type=\"button\" class=\"product-add-btn\" onclick=\"openPmoModal(this, {{ product.product_id }})\">\n"
    "                <i class=\"fas fa-cart-plus\"></i> Th\u00eam v\u00e0o gi\u1ecf\n"
    "              </button>\n"
    "            </div>\n"
    "          </div>\n"
    "          {% endfor %}\n"
    "        {% else %}\n"
    "          <div class=\"product-empty\"><i class=\"fas fa-box-open\"></i><p>Ch\u01b0a c\u00f3 s\u1ea3n ph\u1ea9m m\u1edbi</p></div>\n"
    "        {% endif %}\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"tab-hot\" class=\"tab-content\">\n"
    "      <div class=\"products-grid\">\n"
    "        {% if featured_products %}\n"
    "          {% for product in featured_products %}\n"
    "          <div class=\"product-card\">\n"
    "            <a href=\"/Products/{{ product.product_id }}\" class=\"product-img\">\n"
    "              {% if product.is_hot %}<span class=\"product-badge badge-hot\">Hot</span>{% endif %}\n"
    "              {% if product.is_new %}<span class=\"product-badge badge-new\" style=\"left:58px\">M\u1edbi</span>{% endif %}\n"
    "              {% if product.discount_percent > 0 %}<span class=\"product-discount\">-{{ product.discount_percent }}%</span>{% endif %}\n"
    "              <img src=\"{% set imgs = product.product_images|selectattr('is_primary')|list %}{% if imgs and imgs[0].image_url %}{{ imgs[0].image_url }}{% elif product.image_url %}{{ product.image_url }}{% elif product.product_images %}{{ product.product_images[0].image_url }}{% else %}/static/images/no-image.png{% endif %}\" alt=\"{{ product.name }}\" onerror=\"this.src='/static/images/no-image.png'\" />\n"
    "            </a>\n"
    "            <div class=\"product-body\">\n"
    "              <a href=\"/Products/{{ product.product_id }}\" class=\"product-name\">{{ product.name }}</a>\n"
    "              <div class=\"product-rating\">\n"
    "                <span class=\"product-stars\"><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star\"></i><i class=\"fas fa-star-half-alt\"></i></span>\n"
    "                <span class=\"product-reviews\">({{ product.rating | default(4.5) }})</span>\n"
    "              </div>\n"
    "              <div class=\"product-price-wrap\">\n"
    "                <span class=\"product-price\">{{ \"{:,.0f}\".format(product.price | float) if product.price else '0' }} \u0111</span>\n"
    "                {% if product.original_price and product.original_price > product.price %}\n"
    "                <span class=\"product-price-orig\">{{ \"{:,.0f}\".format(product.original_price | float) }} \u0111</span>\n"
    "                {% endif %}\n"
    "              </div>\n"
    "              <button type=\"button\" class=\"product-add-btn\" onclick=\"openPmoModal(this, {{ product.product_id }})\">\n"
    "                <i class=\"fas fa-cart-plus\"></i> Th\u00eam v\u00e0o gi\u1ecf\n"
    "              </button>\n"
    "            </div>\n"
    "          </div>\n"
    "          {% endfor %}\n"
    "        {% else %}\n"
    "          <div class=\"product-empty\"><i class=\"fas fa-fire-alt\"></i><p>Ch\u01b0a c\u00f3 s\u1ea3n ph\u1ea9m hot</p></div>\n"
    "        {% endif %}\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "</section>\n"
    "\n"
    "<!-- WHY US -->\n"
    "<section class=\"section\">\n"
    "  <div class=\"container\">\n"
    "    <div class=\"section-header\" style=\"justify-content:center;text-align:center;flex-direction:column;align-items:center\">\n"
    "      <div class=\"section-label\">T\u1ea1i sao ch\u1ecdn</div>\n"
    "      <div class=\"section-title\">Ch\u00fang t\u00f4i l\u00e0 l\u1ef1a ch\u1ecdn s\u1ed1 1</div>\n"
    "    </div>\n"
    "    <div class=\"why-grid\">\n"
    "      <div class=\"why-card\"><div class=\"why-icon blue\"><i class=\"fas fa-shield-check\"></i></div><div class=\"why-title\">100% Ch\u00ednh h\u00e3ng</div><div class=\"why-desc\">Cam k\u1ebft s\u1ea3n ph\u1ea9m ch\u00ednh h\u00e3ng, c\u00f3 \u0111\u1ea7y \u0111\u1ee7 gi\u1ea5y t\u1edd v\u00e0 b\u1ea3o h\u00e0nh t\u1eeb nh\u00e0 s\u1ea3n xu\u1ea5t.</div></div>\n"
    "      <div class=\"why-card\"><div class=\"why-icon green\"><i class=\"fas fa-tags\"></i></div><div class=\"why-title\">Gi\u00e1 t\u1ed1t nh\u1ea5t</div><div class=\"why-desc\">Gi\u00e1 c\u1ea1nh tranh nh\u1ea5t th\u1ecb tr\u01b0\u1eddng v\u1edbi nhi\u1ec1u \u01b0u \u0111\u00e3i h\u1ea5p d\u1eabn m\u1ed7i ng\u00e0y.</div></div>\n"
    "      <div class=\"why-card\"><div class=\"why-icon amber\"><i class=\"fas fa-shipping-fast\"></i></div><div class=\"why-title\">Giao h\u00e0ng nhanh</div><div class=\"why-desc\">Giao h\u00e0ng trong 2-4 gi\u1edd n\u1ed9i th\u00e0nh. Mi\u1ec5n ph\u00ed v\u1eadn chuy\u1ec3n cho \u0111\u01a1n t\u1eeb 500.000\u0111.</div></div>\n"
    "      <div class=\"why-card\"><div class=\"why-icon purple\"><i class=\"fas fa-undo\"></i></div><div class=\"why-title\">\u0110\u1ed5i tr\u1ea3 d\u1ec5 d\u00e0ng</div><div class=\"why-desc\">\u0110\u1ed5i tr\u1ea3 mi\u1ec5n ph\u00ed trong 7 ng\u00e0y n\u1ebfu s\u1ea3n ph\u1ea9m kh\u00f4ng \u0111\u00fang nh\u01b0 m\u00f4 t\u1ea3.</div></div>\n"
    "      <div class=\"why-card\"><div class=\"why-icon rose\"><i class=\"fas fa-headset\"></i></div><div class=\"why-title\">H\u1ed7 tr\u1ee3 24/7</div><div class=\"why-desc\">\u0110\u1ed9i ng\u0169 t\u01b0 v\u1ea5n v\u00e0 tr\u1ee3 l\u00fd AI s\u1eb5n s\u00e0ng h\u1ed7 tr\u1ee3 b\u1ea1n m\u1ecdi l\u00fac, m\u1ecdi n\u01a1i.</div></div>\n"
    "      <div class=\"why-card\"><div class=\"why-icon dark\"><i class=\"fas fa-lock\"></i></div><div class=\"why-title\">Thanh to\u00e1n an to\u00e0n</div><div class=\"why-desc\">COD, chuy\u1ec3n kho\u1ea3n, th\u1ebb t\u00edn d\u1ee5ng, v\u00ed \u0111i\u1ec7n t\u1eeb - t\u1ea5t c\u1ea3 \u0111\u1ec1u an to\u00e0n.</div></div>\n"
    "    </div>\n"
    "  </div>\n"
    "</section>\n"
    "\n"
    "<!-- SUPPORT BANNER -->\n"
    "<section class=\"support-banner\">\n"
    "  <div class=\"container\">\n"
    "    <h2 class=\"support-title\">B\u1ea1n c\u1ea7n h\u1ed7 tr\u1ee3?</h2>\n"
    "    <p class=\"support-sub\">\u0110\u1ed9i ng\u0169 h\u1ed7 tr\u1ee3 c\u1ee7a ch\u00fang t\u00f4i lu\u00f4n s\u1eb5n s\u00e0ng gi\u00fap b\u1ea1n</p>\n"
    "    <div class=\"support-hotline\"><i class=\"fas fa-phone-alt\"></i> 1800.6601</div>\n"
    "    <div class=\"support-btns\">\n"
    "      <a href=\"tel:18006601\" class=\"support-btn support-btn-phone\"><i class=\"fas fa-phone-alt\"></i> G\u1ecdi ngay</a>\n"
    "      <a href=\"/Chat/\" class=\"support-btn support-btn-chat\"><i class=\"fas fa-comments\"></i> Chat v\u1edbi AI</a>\n"
    "    </div>\n"
    "  </div>\n"
    "</section>\n"
    "\n"
    "<!-- PMO MODAL -->\n"
    "<div class=\"pmo-overlay\" id=\"pmo-overlay\" onclick=\"if(event.target===this)pmoClose()\">\n"
    "  <div class=\"pmo-modal\" id=\"pmo-modal\"><div class=\"pmo-loading\"><i class=\"fas fa-spinner fa-spin\" style=\"margin-right:7px\"></i> \u0110ang t\u1ea3i...</div></div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "(function(){\n"
    "  var pmoOverlay=document.getElementById('pmo-overlay');\n"
    "  var pmoModal=document.getElementById('pmo-modal');\n"
    "\n"
    "  window.openPmoModal=function(btn,productId){\n"
    "    pmoOverlay.classList.add('active');\n"
    "    document.body.style.overflow='hidden';\n"
    "    pmoModal.innerHTML='<div class=\"pmo-loading\"><i class=\"fas fa-spinner fa-spin\" style=\"margin-right:7px\"></i> \u0110ang t\u1ea3i...</div>';\n"
    "    fetch('/Products/'+productId+'/variants')\n"
    "      .then(function(r){return r.json();})\n"
    "      .then(function(data){\n"
    "        var card=btn?btn.closest('.product-card'):null;\n"
    "        var name=card?card.querySelector('.product-name'):null;\n"
    "        var priceEl=card?card.querySelector('.product-price'):null;\n"
    "        var imgEl=card?card.querySelector('.product-img img'):null;\n"
    "        var pName=name?name.textContent.trim():'S\u1ea3n ph\u1ea9m';\n"
    "        var pPrice=priceEl?priceEl.textContent.trim():'0';\n"
    "        var pImg=imgEl?imgEl.src:'';\n"
    "        if(!data.success||!data.variants||data.variants.length===0){\n"
    "          pmoModal.innerHTML=buildSimple(productId,pName,pPrice,pImg);\n"
    "          return;\n"
    "        }\n"
    "        pmoModal.innerHTML=buildFull(productId,pName,pPrice,pImg,data.variants);\n"
    "      })\n"
    "      .catch(function(){\n"
    "        pmoModal.innerHTML='<div style=\"padding:32px;text-align:center;color:var(--rose)\"><i class=\"fas fa-exclamation-circle\"></i> Kh\u00f4ng th\u1ec3 t\u1ea3i s\u1ea3n ph\u1ea9m.</div>';\n"
    "      });\n"
    "  };\n"
    "\n"
    "  window.pmoClose=function(){pmoOverlay.classList.remove('active');document.body.style.overflow='';};\n"
    "\n"
    "  window.pmoAddToCart=function(productId){\n"
    "    var variantId=null;\n"
    "    var sel=document.querySelector('.pmo-opt.selected[data-variant-id]');\n"
    "    if(sel&&sel.dataset.variantId)variantId=sel.dataset.variantId;\n"
    "    var qty=parseInt(document.getElementById('pmo-qty-val').textContent)||1;\n"
    "    var btn=document.getElementById('pmo-add-btn');\n"
    "    if(btn){btn.disabled=true;btn.innerHTML='<i class=\"fas fa-spinner fa-spin\"></i> \u0110ang th\u00eam...'}\n"
    "    var fd=new URLSearchParams();fd.append('quantity',qty);\n"
    "    if(variantId)fd.append('variant_id',variantId);\n"
    "    fetch('/Products/'+productId+'/add-to-cart',{\n"
    "      method:'POST',\n"
    "      headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json','X-Requested-With':'XMLHttpRequest'},\n"
    "      body:fd\n"
    "    })\n"
    "    .then(function(r){\n"
    "      var ct=r.headers.get('Content-Type')||'';\n"
    "      if(!ct.includes('application/json')){\n"
    "        if(r.status===401||r.status===303){r.json().then(function(d){if(d.login_url)window.location.href=d.login_url;});}\n"
    "        else{pmoClose();location.reload();}\n"
    "        return;\n"
    "      }\n"
    "      return r.json();\n"
    "    })\n"
    "    .then(function(d){\n"
    "      if(!d)return;\n"
    "      if(d.success){\n"
    "        pmoClose();\n"
    "        if(typeof showNotification==='function')showNotification(d.message||'\u0110\u00e3 th\u00eam v\u00e0o gi\u1ecf h\u00e0ng!','success');\n"
    "        if(d.cart_count!==undefined&&typeof updateCartCount==='function')updateCartCount(d.cart_count);\n"
    "      } else {\n"
    "        if(d.login_url)window.location.href=d.login_url;\n"
    "        else{if(typeof showNotification==='function')showNotification(d.message||'C\u00f3 l\u1ed7i x\u1ea3y ra!','danger');}\n"
    "        if(btn){btn.disabled=false;btn.innerHTML='<i class=\"fas fa-cart-plus\"></i> Th\u00eam v\u00e0o gi\u1ecf h\u00e0ng'}\n"
    "      }\n"
    "    })\n"
    "    .catch(function(){\n"
    "      if(typeof showNotification==='function')showNotification('C\u00f3 l\u1ed7i x\u1ea3y ra, vui l\u00f2ng th\u1eed l\u1ea1i!','danger');\n"
    "      if(btn){btn.disabled=false;btn.innerHTML='<i class=\"fas fa-cart-plus\"></i> Th\u00eam v\u00e0o gi\u1ecf h\u00e0ng'}\n"
    "    });\n"
    "  };\n"
    "\n"
    "  function buildHdr(id,name,price,img){\n"
    "    return '<div class=\"pmo-hdr\"><div class=\"pmo-thumb\"><img src=\"'+(img||'/static/images/no-image.png')+'\" onerror=\"this.src=\\'/static/images/no-image.png\\'\"></div><div class=\"pmo-info\"><div class=\"pmo-name\">'+esc(name)+'</div><div class=\"pmo-price\">'+price+'</div></div><button class=\"pmo-close\" onclick=\"pmoClose()\"><i class=\"fas fa-times\"></i></button></div>';\n"
    "  }\n"
    "  function buildSimple(id,name,price,img){\n"
    "    return buildHdr(id,name,price,img)+\n"
    "      '<div class=\"pmo-body\"><div class=\"pmo-qty\"><span class=\"pmo-qty-lbl\">S\u1ed1 l\u01b0\u1ee3ng</span><div class=\"pmo-qty-ctrl\"><button class=\"pmo-qty-btn\" onclick=\"pmoChangeQty(-1)\">-</button><span class=\"pmo-qty-val\" id=\"pmo-qty-val\">1</span><button class=\"pmo-qty-btn\" onclick=\"pmoChangeQty(1)\">+</button></div></div></div><div class=\"pmo-foot\"><button class=\"pmo-add-btn\" id=\"pmo-add-btn\" onclick=\"pmoAddToCart('+id+')\"><i class=\"fas fa-cart-plus\"></i> Th\u00eam v\u00e0o gi\u1ecf h\u00e0ng</button></div>';\n"
    "  }\n"
    "  function buildFull(id,name,price,img,variants){\n"
    "    var colors={},vMap={};\n"
    "    variants.forEach(function(v){vMap[v.variant_id]=v;if(v.color&&v.color_hex)colors[v.color]={hex:v.color_hex,vid:v.variant_id};});\n"
    "    var html=buildHdr(id,name,price,img)+'<div class=\"pmo-body\">';\n"
    "    if(Object.keys(colors).length>0){\n"
    "      html+='<div class=\"pmo-opt-label\">M\u00e0u s\u1eafc</div><div class=\"pmo-opt-row\">';\n"
    "      Object.keys(colors).forEach(function(c,i){\n"
    "        var h=colors[c].hex||'#ccc';\n"
    "        html+='<button class=\"pmo-opt'+(i===0?' selected':'')+'\" data-type=\"color\" data-value=\"'+esc(c)+'\" data-variant-id=\"'+colors[c].vid+'\" onclick=\"pmoSelectOpt(this)\"><span class=\"pmo-dot\" style=\"background:'+h+'\"></span>'+esc(c)+'</button>';\n"
    "      });\n"
    "      html+='</div>';\n"
    "    }\n"
    "    html+='<div class=\"pmo-qty\"><span class=\"pmo-qty-lbl\">S\u1ed1 l\u01b0\u1ee3ng</span><div class=\"pmo-qty-ctrl\"><button class=\"pmo-qty-btn\" onclick=\"pmoChangeQty(-1)\">-</button><span class=\"pmo-qty-val\" id=\"pmo-qty-val\">1</span><button class=\"pmo-qty-btn\" onclick=\"pmoChangeQty(1)\">+</button></div></div></div><div class=\"pmo-foot\"><button class=\"pmo-add-btn\" id=\"pmo-add-btn\" onclick=\"pmoAddToCart('+id+')\"><i class=\"fas fa-cart-plus\"></i> Th\u00eam v\u00e0o gi\u1ecf h\u00e0ng</button></div>';\n"
    "    window.__pmoMap=vMap;\n"
    "    return html;\n"
    "  }\n"
    "  window.pmoSelectOpt=function(el){\n"
    "    el.parentElement.querySelectorAll('.pmo-opt').forEach(function(b){b.classList.remove('selected');});\n"
    "    el.classList.add('selected');\n"
    "    if(el.dataset.variantId){\n"
    "      var v=window.__pmoMap[el.dataset.variantId];\n"
    "      if(v&&v.price){var pe=document.querySelector('.pmo-price');if(pe)pe.textContent=Number(v.price).toLocaleString('vi-VN',{minimumFractionDigits:0})+' \u0111';}\n"
    "    }\n"
    "  };\n"
    "  window.pmoChangeQty=function(d){\n"
    "    var el=document.getElementById('pmo-qty-val');\n"
    "    if(!el)return;\n"
    "    el.textContent=Math.max(1,(parseInt(el.textContent)||1)+d);\n"
    "  };\n"
    "  function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML;}\n"
    "\n"
    "  window.switchTab=function(evt,tabName){\n"
    "    var tc=document.getElementsByClassName('tab-content');\n"
    "    for(var i=0;i<tc.length;i++)tc[i].classList.remove('active');\n"
    "    var tb=document.getElementsByClassName('tab-btn');\n"
    "    for(var i=0;i<tb.length;i++)tb[i].classList.remove('active');\n"
    "    document.getElementById(tabName).classList.add('active');\n"
    "    evt.currentTarget.classList.add('active');\n"
    "  };\n"
    "})();\n"
    "</script>\n"
    "{% endblock %}\n"
)

p = Path(r"d:\a_LTPY\BTLPYTHON\Website-ban-do-cong-nghe-AI-G4-14.1-Y3\Views\Home\index.html")
p.write_text(content, encoding='utf-8')
print(f"index.html written: {len(content)} chars")
