# -*- coding: utf-8 -*-
from pathlib import Path

content = (
    "<!doctype html>\n"
    "<html lang=\"vi\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\" />\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
    "  <title>Tech Store AI</title>\n"
    "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\n"
    "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\" />\n"
    "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\" />\n"
    "  <link rel=\"stylesheet\" href=\"/static/css/style.css?v=6\" />\n"
    "  <link rel=\"icon\" type=\"image/svg+xml\" href=\"/static/favicon.svg\" />\n"
    "  {% block extra_head %}{% endblock %}\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "  <!-- NAVIGATION BAR -->\n"
    "  <nav class=\"nav-bar\" id=\"nav-bar\">\n"
    "    <div class=\"nav-inner\">\n"
    "\n"
    "      <!-- Logo -->\n"
    "      <a href=\"/\" class=\"nav-logo\">\n"
    "        <div class=\"nav-logo-icon\"><i class=\"fas fa-robot\"></i></div>\n"
    "        <div class=\"nav-logo-name\">Tech Store AI</div>\n"
    "      </a>\n"
    "\n"
    "      <!-- Nav Links -->\n"
    "      <ul class=\"nav-links\">\n"
    "        <li><a href=\"/\" class=\"nav-link\"><i class=\"fas fa-home\"></i></a></li>\n"
    "        <li><a href=\"/Products/\" class=\"nav-link\">S\u1ea3n ph\u1ea9m</a></li>\n"
    "        <li><a href=\"/Cart/\" class=\"nav-link\">Gi\u1ecf h\u00e0ng</a></li>\n"
    "        <li><a href=\"/Chat/\" class=\"nav-link ai\"><i class=\"fas fa-robot\"></i> AI T\u01b0 v\u1ea5n</a></li>\n"
    "        <li><a href=\"/Products/?sort=new\" class=\"nav-link new\"><i class=\"fas fa-bolt\"></i> M\u1edbi nh\u1ea5t</a></li>\n"
    "        <li><a href=\"/Products/?sort=hot\" class=\"nav-link hot\"><i class=\"fas fa-fire\"></i> Hot</a></li>\n"
    "      </ul>\n"
    "\n"
    "      <!-- Actions -->\n"
    "      <div class=\"nav-actions\">\n"
    "        <a href=\"/Cart/\" class=\"nav-action\">\n"
    "          <div class=\"nav-action-icon\"><i class=\"fas fa-shopping-bag\"></i></div>\n"
    "          <div class=\"nav-action-badge\">{{ cart_count | default(0) }}</div>\n"
    "          <div class=\"nav-action-label\">Gi\u1ecf h\u00e0ng</div>\n"
    "        </a>\n"
    "        {% if current_user %}\n"
    "        <div class=\"nav-user\">\n"
    "          <a href=\"#\" class=\"nav-action\" onclick=\"return false\" id=\"nav-user-btn\">\n"
    "            <div class=\"nav-action-icon\" style=\"color:var(--blue)\"><i class=\"fas fa-circle-user\"></i></div>\n"
    "            <div class=\"nav-action-label\" style=\"color:var(--blue)\">{{ current_user.full_name or current_user.username }}</div>\n"
    "          </a>\n"
    "          <div class=\"nav-user-drop\" id=\"nav-user-drop\">\n"
    "            <a href=\"/Auth/Profile\" class=\"nav-drop-item\"><i class=\"fas fa-user\"></i> Th\u00f4ng tin c\u00e1 nh\u00e2n</a>\n"
    "            <a href=\"/Orders/\" class=\"nav-drop-item\"><i class=\"fas fa-receipt\"></i> \u0110\u01a1n h\u00e0ng</a>\n"
    "            {% if current_user.role_name == 'Admin' %}\n"
    "            <a href=\"/Admin/Dashboard\" class=\"nav-drop-item\"><i class=\"fas fa-cog\"></i> Qu\u1ea3n l\u00fd Admin</a>\n"
    "            {% endif %}\n"
    "            <div class=\"nav-drop-divider\"></div>\n"
    "            <a href=\"/Auth/Logout\" class=\"nav-drop-item danger\"><i class=\"fas fa-sign-out-alt\"></i> \u0110\u0103ng xu\u1ea5t</a>\n"
    "          </div>\n"
    "        </div>\n"
    "        {% else %}\n"
    "        <a href=\"/Auth/Login\" class=\"nav-action\">\n"
    "          <div class=\"nav-action-icon\"><i class=\"fas fa-user\"></i></div>\n"
    "          <div class=\"nav-action-label\">\u0110\u0103ng nh\u1eadp</div>\n"
    "        </a>\n"
    "        {% endif %}\n"
    "      </div>\n"
    "    </div>\n"
    "  </nav>\n"
    "\n"
    "  {% block content %}{% endblock %}\n"
    "\n"
    "  {% include \"partials/footer.html\" %}\n"
    "  {% include \"partials/chatbot.html\" %}\n"
    "\n"
    "  <div id=\"toast-container\" aria-live=\"polite\" aria-atomic=\"true\"></div>\n"
    "\n"
    "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
    "  <script src=\"/static/js/main.js?v=6\"></script>\n"
    "  <script>\n"
    "  (function(){\n"
    "    /* User dropdown */\n"
    "    var um = document.querySelector('.nav-user');\n"
    "    if (um && document.getElementById('nav-user-drop')) {\n"
    "      document.getElementById('nav-user-btn').addEventListener('click', function(e) {\n"
    "        e.preventDefault();\n"
    "        e.stopPropagation();\n"
    "        document.getElementById('nav-user-drop').classList.toggle('show');\n"
    "      });\n"
    "      document.addEventListener('click', function(e) {\n"
    "        if (!um.contains(e.target))\n"
    "          document.getElementById('nav-user-drop').classList.remove('show');\n"
    "      });\n"
    "    }\n"
    "    /* Nav bar scroll shadow */\n"
    "    window.addEventListener('scroll', function() {\n"
    "      var h = document.getElementById('nav-bar');\n"
    "      if (h) h.classList.toggle('scrolled', window.scrollY > 5);\n"
    "    });\n"
    "  })();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n"
)

p = Path(r"d:\a_LTPY\BTLPYTHON\Website-ban-do-cong-nghe-AI-G4-14.1-Y3\Views\Shared\base.html")
p.write_text(content, encoding='utf-8')
print(f"base.html written: {len(content)} chars")
