# -*- coding: utf-8 -*-
from pathlib import Path

content = (
    "<!doctype html>\n"
    "<html lang=\"vi\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\" />\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
    "  <title>Tech Store AI</title>\n"
    "  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\n"
    "  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\" />\n"
    "  <link href=\"https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\" />\n"
    "  <link rel=\"stylesheet\" href=\"/static/css/style.css?v=5\" />\n"
    "  <link rel=\"icon\" type=\"image/svg+xml\" href=\"/static/favicon.svg\" />\n"
    "  {% block extra_head %}{% endblock %}\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "  <!-- UNIFIED PREMIUM HEADER -->\n"
    "  <header class=\"premium-header\" id=\"premium-header\">\n"
    "    <div class=\"premium-header-inner\">\n"
    "\n"
    "      <!-- Logo -->\n"
    "      <a href=\"/\" class=\"premium-logo\">\n"
    "        <div class=\"premium-logo-icon\"><i class=\"fas fa-robot\"></i></div>\n"
    "        <div>\n"
    "          <div class=\"premium-logo-name\">Tech <span>Store</span> AI</div>\n"
    "          <div class=\"premium-logo-sub\">C\u00f4ng ngh\u1ec7 th\u00f4ng minh</div>\n"
    "        </div>\n"
    "      </a>\n"
    "\n"
    "      <!-- Search -->\n"
    "      <form action=\"/Products/\" method=\"GET\" class=\"premium-search\">\n"
    "        <div class=\"premium-search-box\">\n"
    "          <i class=\"fas fa-search premium-search-icon\"></i>\n"
    "          <input type=\"text\" name=\"search\" placeholder=\"T\u00ecm ki\u1ebfm s\u1ea3n ph\u1ea9m...\" value=\"{{ search | default('') }}\" />\n"
    "        </div>\n"
    "        <button type=\"submit\"><i class=\"fas fa-search\"></i></button>\n"
    "      </form>\n"
    "\n"
    "      <!-- Actions -->\n"
    "      <div class=\"premium-actions\">\n"
    "        <a href=\"/Cart/\" class=\"premium-action\">\n"
    "          <div class=\"premium-action-icon\">\n"
    "            <i class=\"fas fa-shopping-bag\"></i>\n"
    "            <span class=\"premium-action-badge\">{{ cart_count | default(0) }}</span>\n"
    "          </div>\n"
    "          <div class=\"premium-action-label\">Gi\u1ecf h\u00e0ng</div>\n"
    "        </a>\n"
    "        {% if current_user %}\n"
    "        <div class=\"premium-user\">\n"
    "          <a href=\"#\" class=\"premium-action\" onclick=\"return false\" id=\"premium-user-btn\">\n"
    "            <div class=\"premium-action-icon\" style=\"color:#93C5FD\"><i class=\"fas fa-circle-user\"></i></div>\n"
    "            <div class=\"premium-action-label\" style=\"color:#93C5FD\">{{ current_user.full_name or current_user.username }}</div>\n"
    "          </a>\n"
    "          <div class=\"premium-user-drop\" id=\"premium-user-drop\">\n"
    "            <a href=\"/Auth/Profile\" class=\"premium-drop-item\"><i class=\"fas fa-user\"></i> Th\u00f4ng tin c\u00e1 nh\u00e2n</a>\n"
    "            <a href=\"/Orders/\" class=\"premium-drop-item\"><i class=\"fas fa-receipt\"></i> \u0110\u01a1n h\u00e0ng</a>\n"
    "            {% if current_user.role_name == 'Admin' %}\n"
    "            <a href=\"/Admin/Dashboard\" class=\"premium-drop-item\"><i class=\"fas fa-cog\"></i> Qu\u1ea3n l\u00fd Admin</a>\n"
    "            {% endif %}\n"
    "            <div class=\"premium-drop-divider\"></div>\n"
    "            <a href=\"/Auth/Logout\" class=\"premium-drop-item danger\"><i class=\"fas fa-sign-out-alt\"></i> \u0110\u0103ng xu\u1ea5t</a>\n"
    "          </div>\n"
    "        </div>\n"
    "        {% else %}\n"
    "        <a href=\"/Auth/Login\" class=\"premium-action\">\n"
    "          <div class=\"premium-action-icon\"><i class=\"fas fa-user\"></i></div>\n"
    "          <div class=\"premium-action-label\">\u0110\u0103ng nh\u1eadp</div>\n"
    "        </a>\n"
    "        {% endif %}\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- Nav strip below header -->\n"
    "    <div class=\"premium-nav\">\n"
    "      <div class=\"premium-nav-inner\">\n"
    "        <button class=\"premium-nav-cats\" id=\"premium-cats-btn\">\n"
    "          <i class=\"fas fa-bars\"></i>\n"
    "          <span>Danh m\u1ee5c</span>\n"
    "        </button>\n"
    "        <nav class=\"premium-nav-links\">\n"
    "          <a href=\"/\" class=\"premium-nav-link\"><i class=\"fas fa-home\"></i> Trang ch\u1ee7</a>\n"
    "          <a href=\"/Products/\" class=\"premium-nav-link\">S\u1ea3n ph\u1ea9m</a>\n"
    "          <a href=\"/Cart/\" class=\"premium-nav-link\">Gi\u1ecf h\u00e0ng</a>\n"
    "          <a href=\"/Chat/\" class=\"premium-nav-link ai\"><i class=\"fas fa-robot\"></i> AI T\u01b0 v\u1ea5n</a>\n"
    "          <a href=\"/Products/?sort=new\" class=\"premium-nav-link new\"><i class=\"fas fa-bolt\"></i> M\u1edbi nh\u1ea5t</a>\n"
    "          <a href=\"/Products/?sort=hot\" class=\"premium-nav-link hot\"><i class=\"fas fa-fire\"></i> Hot</a>\n"
    "        </nav>\n"
    "        <div class=\"premium-nav-support\"><i class=\"fas fa-headset\"></i> 1800.6601</div>\n"
    "      </div>\n"
    "    </div>\n"
    "  </header>\n"
    "\n"
    "  {% block content %}{% endblock %}\n"
    "\n"
    "  {% include \"partials/footer.html\" %}\n"
    "  {% include \"partials/chatbot.html\" %}\n"
    "\n"
    "  <div id=\"toast-container\" aria-live=\"polite\" aria-atomic=\"true\"></div>\n"
    "\n"
    "  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n"
    "  <script src=\"/static/js/main.js?v=5\"></script>\n"
    "  <script>\n"
    "  (function(){\n"
    "    var um = document.querySelector('.premium-user');\n"
    "    if (um && document.getElementById('premium-user-drop')) {\n"
    "      document.getElementById('premium-user-btn').addEventListener('click', function(e) {\n"
    "        e.preventDefault();\n"
    "        e.stopPropagation();\n"
    "        document.getElementById('premium-user-drop').classList.toggle('show');\n"
    "      });\n"
    "      document.addEventListener('click', function(e) {\n"
    "        if (!um.contains(e.target))\n"
    "          document.getElementById('premium-user-drop').classList.remove('show');\n"
    "      });\n"
    "    }\n"
    "    window.addEventListener('scroll', function() {\n"
    "      var h = document.getElementById('premium-header');\n"
    "      if (h) h.classList.toggle('scrolled', window.scrollY > 5);\n"
    "    });\n"
    "  })();\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n"
)

p = Path(r"d:\a_LTPY\BTLPYTHON\Website-ban-do-cong-nghe-AI-G4-14.1-Y3\Views\Shared\base.html")
p.write_text(content, encoding='utf-8')
print(f"Written: {len(content)} chars")
