# Generated by Django 5.2.14 on 2026-05-07 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(verbose_name='Session ID')),
                ('user_message', models.TextField(verbose_name='Tin nhắn user')),
                ('ai_response', models.TextField(verbose_name='Phản hồi AI')),
                ('intent_detected', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intent phát hiện')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Độ chính xác')),
                ('was_escalated', models.BooleanField(default=False, verbose_name='Được chuyển sang nhân viên')),
                ('user_rating', models.IntegerField(blank=True, null=True, verbose_name='Đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
            ],
            options={
                'verbose_name': 'Log AI',
                'verbose_name_plural': 'Log AI',
                'db_table': 'AIConversationLogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Đang chat'), ('Waiting', 'Đang chờ'), ('Closed', 'Đã đóng')], default='Waiting', max_length=20, verbose_name='Trạng thái')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('account', models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên chat',
                'verbose_name_plural': 'Phiên chat',
                'db_table': 'ChatSessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('sender_type', models.CharField(choices=[('user', 'Khách hàng'), ('admin', 'Nhân viên'), ('bot', 'Bot')], max_length=10, verbose_name='Người gửi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'db_table': 'ChatMessages',
                'ordering': ['created_at'],
            },
        ),
    ]
