# Generated by Django 5.2.14 on 2026-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('product', 'San pham'), ('faq', 'Cau hoi thuong gap'), ('policy', 'Chinh sach')], db_index=True, max_length=20, verbose_name='Loai nguon')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='ID nguon')),
                ('content', models.TextField(verbose_name='Noi dung')),
                ('category', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Danh muc')),
                ('priority', models.IntegerField(default=1, verbose_name='Uu tien')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Vector embedding')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kich hoat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngay cap nhat')),
            ],
            options={
                'verbose_name': 'Kien thuc chatbot',
                'verbose_name_plural': 'Kien thuc chatbot',
                'db_table': 'KnowledgeChunks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
